export const GET_STUDENTS_FETCHING = 'GET_STUDENTS_FETCHING';
export const GET_STUDENTS_FULFILLED = 'GET_STUDENTS_FULFILLED';
export const GET_STUDENTS_REJECTED = 'GET_STUDENTS_REJECTED';

export const ADD_STUDENT_FETCHING = 'ADD_STUDENT_FETCHING';
export const ADD_STUDENT_FULFILLED = 'ADD_STUDENT_FULFILLED';
export const ADD_STUDENT_REJECTED = 'ADD_STUDENT_REJECTED';

export const DELETE_STUDENT_FETCHING = 'DELETE_STUDENT_FETCHING';
export const DELETE_STUDENT_FULFILLED = 'DELETE_STUDENT_FULFILLED';
export const DELETE_STUDENT_REJECTED = 'DELETE_STUDENT_REJECTED';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
